

services:
  web:
    build:
      context: .
    volumes:
      - static_volume:/app/static
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  static_volume:
